version: '3'
services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    # command: gunicorn myviews.wsgi:application --bind 0.0.0.0:8080
    restart: always
    command: python3 main.py
    volumes:
      - .:/riche
